
     spring:
       # ???????
       datasource:
         driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL ???8.0+ ?? cj?
         url: jdbc:mysql://localhost:3306/phone_repair?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
         # ???url ? phone_repair ???????????????GMT%2B8 ??????
         username: root  # ?? MySQL ???
         password: 123456  # ?? MySQL ??
       # DevTools ?????
       devtools:
         restart:
           enabled: true  # ?????
           additional-paths: src/main/java  # ?? Java ????

     # ????
     logging:
       charset:
         console: UTF-8  # ???????
       level:
         com.yjx.mapper: trace  # ?? Mapper ?? SQL ????????

     # MyBatis ??
     mybatis:
       type-aliases-package: com.yjx.pojo  # ? pojo ????????XML ????????

     # ????
     server:
       port: 8081  # ?????????????????
       servlet:
         context-path: /yjx  # ?????????????????? http://localhost:8081/yjx/xxx?